language: go
sudo: false
before_install:
  - rvm list
  - rvm install 2.2.0
  - rvm use 2.2.0 --default
script:
  - go test -v .
  - bundle install && bundle exec rake build
  - bundle exec rake cucumber
